### ISSUE TITLE
Doesn't start anymore on Windows 10

### ISSUE THREAD

**Issue by zagi988** [gawindx/WinNUT-Client#119]
Here's what happens, doesn't even open the app.

`Exception type: System.TypeInitializationException
Exception message: The type initializer for 'WinNUT_client.WinNUT_Params' threw an exception.
Exception stack trace: 
   at WinNUT_client.WinNUT_Params.Init_Params()
   at WinNUT_client.WinNUT.WinNUT_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by gbakeman** [comment]
Appears to be a duplicate of #75

**Comment by zagi988** [comment]
Seems so. But my was working for a few months and then out of nowhere - started crashing.
