### ISSUE TITLE
WinNut won't start System.ArgumentNullException error

### ISSUE THREAD

**Issue by danc2112** [gawindx/WinNUT-Client#170]
WinNUT Bug Report
Os Version : 6.2.9200.0
WinNUT Version : 2.1.7740.35837

WinNUT Parameters : 
{
  "Delay": 5000,
  "AutoReconnect": "True",
  "MinInputVoltage": 110,
  "MaxInputVoltage": 130,
  "FrequencySupply": 1,
  "MinInputFrequency": 40,
  "MaxInputFrequency": 60,
  "MinOutputVoltage": 110,
  "MaxOutputVoltage": 130,
  "MinUPSLoad": 0,
  "MaxUPSLoad": 100,
  "MinBattVoltage": 30,
  "MaxBattVoltage": 50,
  "MinimizeToTray": "True",
  "MinimizeOnStart": "True",
  "CloseToTray": "True",
  "StartWithWindows": "True",
  "UseLogFile": "True",
  "Log Level": 1,
  "ShutdownLimitBatteryCharge": 5,
  "ShutdownLimitUPSRemainTime": 120,
  "ImmediateStopAction": "False",
  "Follow_FSD": "False",
  "TypeOfStop": 0,
  "DelayToShutdown": 15,
  "AllowExtendedShutdownDelay": "False",
  "ExtendedShutdownDelay": 15,
  "VerifyUpdate": "True",
  "VerifyUpdateAtStart": "False",
  "DelayBetweenEachVerification": 2,
  "StableOrDevBranch": 0,
  "LastDateVerification": "12/6/2022 10:15:16 AM"
}

Error Message : 
Exception type: System.ArgumentNullException
Exception message: Value cannot be null.
Parameter name: value
Exception stack trace: 
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s, IFormatProvider provider)
   at WinNUT_Client_Common.UPS_Device.Init_Constant(Nut_Socket& Nut_Socket)
   at WinNUT_Client_Common.UPS_Device.Connect_UPS()
   at WinNUT_Client_Common.UPS_Device..ctor(Nut_Parameter Nut_Config, Logger& LogFile)
   at WinNUT_Client.WinNUT.WinNUT_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Last Events :
7/17/2023 10:43:09 AM Pid: 28768 WinNUT : Initialisation Globals Variables Complete
7/17/2023 10:43:09 AM Pid: 28768 WinNUT : Initialisation Params Complete
7/17/2023 10:43:09 AM Pid: 28768 WinNUT : Loaded Params Complete
7/17/2023 10:43:09 AM Pid: 28768 WinNUT : NotifyIcons Initialised
7/17/2023 10:43:09 AM Pid: 28768 WinNUT : Windows 10 Toast Notification Not Available. Too Old Windows Version
7/17/2023 10:43:09 AM Pid: 28768 UPS_Device : TCP Socket Created
7/17/2023 10:43:10 AM Pid: 28768 UPS_Device : Enter GetUPSVar
7/17/2023 10:43:10 AM Pid: 28768 UPS_Device : Enter GetUPSVar
7/17/2023 10:43:10 AM Pid: 28768 UPS_Device : Enter GetUPSVar
7/17/2023 10:43:10 AM Pid: 28768 UPS_Device : Enter GetUPSVar
7/17/2023 10:43:10 AM Pid: 28768 UPS_Device : Enter GetUPSVar

**Comment by gbakeman** [comment]
Please see #136 . This repository is no longer maintained, and development has moved here: https://github.com/nutdotnet/WinNUT-Client

Please consider closing this issue and seeing the new repository for updated releases.
