### ISSUE TITLE
Crashes when I execute - Problem Resolved

### ISSUE THREAD

**Issue by Smarterthanme99** [gawindx/WinNUT-Client#184]
Problems fixed by Downloading newest version v2.3.8800
-----------------------------------------------------------------
How can I change the "Interval" when I get no Config Pop-up window?

WinNUT Bug Report
Os Version : 6.2.9200.0
WinNUT Version : 2.1.7740.35837

WinNUT Parameters : 
{
  "Delay": 0,
  "AutoReconnect": "False",
  "MinInputVoltage": 88,
  "MaxInputVoltage": 140,
  "FrequencySupply": 1,
  "MinInputFrequency": 40,
  "MaxInputFrequency": 60,
  "MinOutputVoltage": 120,
  "MaxOutputVoltage": 120,
  "MinUPSLoad": 0,
  "MaxUPSLoad": 100,
  "MinBattVoltage": 6,
  "MaxBattVoltage": 18,
  "MinimizeToTray": "True",
  "MinimizeOnStart": "True",
  "CloseToTray": "False",
  "StartWithWindows": "True",
  "UseLogFile": "True",
  "Log Level": 0,
  "ShutdownLimitBatteryCharge": 30,
  "ShutdownLimitUPSRemainTime": 120,
  "ImmediateStopAction": "False",
  "Follow_FSD": "False",
  "TypeOfStop": 0,
  "DelayToShutdown": 15,
  "AllowExtendedShutdownDelay": "False",
  "ExtendedShutdownDelay": 15,
  "VerifyUpdate": "False",
  "VerifyUpdateAtStart": "False",
  "DelayBetweenEachVerification": 2,
  "StableOrDevBranch": 0,
  "LastDateVerification": ""
}

Error Message : 
Exception type: System.ArgumentOutOfRangeException
Exception message: Value '0' is not a valid value for Interval. Interval must be greater than 0.
Parameter name: Interval
Exception stack trace: 
   at System.Windows.Forms.Timer.set_Interval(Int32 value)
   at WinNUT_Client.WinNUT.WinNUT_Load(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Last Events :
2024-02-24 1:33:33 AM Pid: 10348 WinNUT : Initialisation Globals Variables Complete
2024-02-24 1:33:33 AM Pid: 10348 WinNUT : Initialisation Params Complete
2024-02-24 1:33:33 AM Pid: 10348 WinNUT : Loaded Params Complete
2024-02-24 1:33:33 AM Pid: 10348 WinNUT : NotifyIcons Initialised
2024-02-24 1:33:33 AM Pid: 10348 WinNUT : Windows 10 Toast Notification Not Available. Too Old Windows Version

**Comment by gbakeman** [comment]
Please see #136
