### ISSUE TITLE
Update loop between v2.0.7721.35955 and vv2.0.7710.35866

### ISSUE THREAD

**Issue by hilari0n** [gawindx/WinNUT-Client#70]
I have WinNUT set to use the "stable" channel for updates.
Version 7.7.1.0 suggested me an update to 2.0.7721. I installed it. The 2.0.7721 version tells me, there's an update, showing changelog for v2.0.7710.35866. If I accept it, the application crashes. Here's the report (cut down a bit):

```
WinNUT Bug Report
Os Version : 6.2.9200.0
WinNUT Version : 2.0.7721.35955

WinNUT Parameters : 
{
  "Delay": 120,
  "AutoReconnect": "True",
  "FrequencySupply": 0,
  "MinUPSLoad": 0,
  "MaxUPSLoad": 0,
  "MinimizeToTray": "False",
  "MinimizeOnStart": "False",
  "CloseToTray": "False",
  "StartWithWindows": "False",
  "UseLogFile": "True",
  "Log Level": 0,
  "ShutdownLimitBatteryCharge": 0,
  "ShutdownLimitUPSRemainTime": 0,
  "ImmediateStopAction": "False",
  "Follow_FSD": "False",
  "TypeOfStop": 1,
  "DelayToShutdown": 0,
  "AllowExtendedShutdownDelay": "False",
  "ExtendedShutdownDelay": 0,
  "VerifyUpdate": "True",
  "VerifyUpdateAtStart": "False",
  "DelayBetweenEachVerification": 2,
  "StableOrDevBranch": 0,
  [...]
}

Error Message : 
Exception type: System.ArgumentNullException
Exception message: Value cannot be null.
Parameter name: uriString
Exception stack trace: 
   at System.Uri..ctor(String uriString)
   at WinNUT_client.Update_Gui.Update_Btn_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
There's nothing on the update in the events from the report.
I have the log file enabled, but it only shows "UPS_Network : Connection to Nut Host Established" entries.

**Comment by gawindx** [comment]
Indeed, an error in the part of the code used to retrieve all the changelogs between the installed version and the new version caused a detection of a non-existent version.
It's fixed and you can update manually to get the version containing the fix.

Oh, version 7.7.10 is a fake tag to allow those who have not yet fetched the versions containing the new update process to be able to do so, otherwise the download could not be completed (version 7.7.1.0 in due to a bug between the old and the new process and corresponding to version 2.0.7710)
